on:
  push:
  pull_request:
    branches:
      - master

jobs:
  unit_test:
    name: 'Unit Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout the repository
      - uses: actions/cache@v2 # Setup cache for node_modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: 'Install dependencies' # Install node_modules
        run: npm ci
      - name: 'Run unit tests' # Run the actual tests
        run: npm test
        env:
          COVERAGE: 1
